bit-country/Metaverse-Network

- luckydraw/lib.rs
- pallets/auction/src/lib.rs
- pallets/nft/src/lib.rs
- pallets/uniqueAsset/src/lib.rs
- runtime/src/lib.rs
Change luckydraw smart contract logic
> implement asset collection

- .gitignore
- Cargo.lock
- pallets/country/Cargo.toml
- pallets/country/src/lib.rs
- pallets/nft/Cargo.toml
- pallets/primitives/src/lib.rs
- pallets/tokenization/Cargo.toml
- pallets/tokenization/src/lib.rs
- pallets/uniqueAsset/Cargo.toml
- pallets/xcm-adapter/Cargo.toml
- pallets/xcm-adapter/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
complete cross chain token transfer with xcm
> cross chain token transfer integrated.

- node/src/chain_spec.rs
- pallets/auction/src/lib.rs
- pallets/auction/src/mock.rs
- pallets/auction/src/tests.rs
- pallets/country/src/lib.rs
- pallets/nft/src/lib.rs
- pallets/primitives/src/lib.rs
Auction handler needs to support different type of assets e.g NFTs, Spot, Country etc. Create a generic creating auction structure and handler.
> Different asset auction handler structure

- pallets/continuum/src/lib.rs
- pallets/continuum/src/types.rs
- pallets/continuum/src/vote.rs
Optimize tally vote calculation logic to handle multiple bidders voting per tally.
> Tally vote calculation logic

- pallets/continuum/src/lib.rs
- pallets/continuum/src/types.rs
> Remove voted out participants from slots

- Cargo.lock
- pallets/auction/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
Complete refactoring auction manager.
> refactor auction manager trait to support continuum and nft

- pallets/auction/src/lib.rs
- pallets/auction/src/mock.rs
- pallets/auction/src/tests.rs
- pallets/nft/src/lib.rs
Added a couple of new error types to go along with test cases.
> Add unit tests to auctions pallet

- Cargo.lock
- node/Cargo.toml
- pallets/xcm-support/Cargo.toml
- pallets/xcm-support/README.md
- pallets/xcm-support/src/currency_adapter.rs
- pallets/xcm-support/src/lib.rs
- pallets/xcm-support/src/tests.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- scripts/Dockerfile
Bumps deps for latest polkadot & substrate rococo-v1 branch
> Bumps deps for latest polkadot & substrate rococo-v1 branch

- pallets/auction/src/mock.rs
Attempt to fix ContinuumHandler Implementation
> add continuum implementation for mock

- .gitignore
- node/src/chain_spec.rs
- pallets/continuum/src/lib.rs
- pallets/continuum/src/mock.rs
- pallets/continuum/src/tests.rs
- runtime/src/constants.rs
- runtime/src/lib.rs
added unit tests for neighborhood finder and register of continuum
> added unit tests for neighborhood finder and register of continuum 

- pallets/continuum/src/lib.rs
- pallets/continuum/src/mock.rs
- pallets/continuum/src/tests.rs
complete unit tests for continuum finalise vote tallies.
> unit tests for rotate_session and calculate continuum good neighbourhood tallies

- metadataType.json
- pallets/auction-manager/Cargo.toml
- pallets/auction-manager/src/lib.rs
- pallets/auction/src/lib.rs
- pallets/auction/src/tests.rs
- pallets/continuum/src/lib.rs
Added buy it now feature in Auction pallet and added/updated unit tests.
> Auction should support buy now which bidder can buy now with fixed price without going through Auction #54

- .github/workflows/rust.yml
- .gitignore
- pallets/bitcountry/Cargo.toml
- pallets/bitcountry/src/mock.rs
- pallets/bitcountry/src/tests.rs
- pallets/continuum/src/mock.rs
- pallets/nft/src/tests.rs
- pallets/tokenization/Cargo.toml
- pallets/tokenization/src/lib.rs
- pallets/tokenization/src/mock.rs
- pallets/tokenization/src/tests.rs
- scripts/Dockerfile
update all test cases to work with latest version
> update all test cases to work with latest version

- pallets/auction/src/lib.rs
- pallets/bitcountry/src/lib.rs
- pallets/bitcountry/src/tests.rs
- pallets/continuum/src/lib.rs
- pallets/continuum/src/mock.rs
- pallets/continuum/src/tests.rs
- pallets/nft/src/lib.rs
- pallets/nft/src/mock.rs
- pallets/nft/src/tests.rs
Upgrade pallet-country and pallet-nft to FRAME V2. 
In order to get this to build and pass tests, there were a couple of lines that appear to be a work in progress that I had to comment out in `pallets/continuum/src/lib.rs` [here](https://github.com/bit-country/Bit-Country-Blockchain/compare/master...ed-iv:more-frame-v2?expand=1#diff-6c549b2e9000d494dc0ee1f55f1f66528dff27becf687a80fbb4c65e795d9591R274-R275)
> More frame v2

- pallets/auction/src/tests.rs
- pallets/nft/src/tests.rs
- pallets/tokenization/src/lib.rs
- pallets/tokenization/src/mock.rs
- pallets/tokenization/src/tests.rs
- runtime/bitcountry/src/lib.rs
- runtime/tewai/src/lib.rs
Added some test castes to tokenization and fixed some failing tests in nft and auction pallets
> Social token tests

- .gitignore
- pallets/auction/Cargo.toml
- pallets/auction/src/lib.rs
- pallets/continuum/src/lib.rs
- pallets/nft/src/lib.rs
- runtime/bitcountry/src/lib.rs
- runtime/tewai/src/lib.rs
- traits/auction-manager/src/lib.rs
This PR created to merge the local and global marketplace concept which allows each bit country can have its own marketplace and trade using their local social currency
> Implement local and global marketplace logic to existing auction pallet

- metadataType.json
- pallets/primitives/src/lib.rs
- pallets/social-currencies/src/lib.rs
- pallets/swap/src/lib.rs
- pallets/tokenization/Cargo.toml
- pallets/tokenization/src/lib.rs
- pallets/tokenization/src/mock.rs
- pallets/tokenization/src/tests.rs
- runtime/bitcountry/src/lib.rs
- runtime/tewai/src/lib.rs
- scripts/docker_run.sh
Allow multi-currency lockable trait. 
Vesting and gradually release social token for bc owner.
> Vesting schedule on new social token. 

- pallets/mining/Cargo.toml
- pallets/mining/src/lib.rs
- pallets/mining/src/mock.rs
- pallets/mining/src/tests.rs
- pallets/primitives/src/lib.rs
- runtime/bitcountry/Cargo.toml
- runtime/bitcountry/src/lib.rs
> mining resource (mintable & burnable) currency system

- pallets/mining/src/lib.rs
- Remove origin check
- Remove from account
> Remove origin check for deposit

- runtime/pioneer/src/weights/module_estate.rs
> Fix build issue

- pallets/auction/src/lib.rs
- pallets/auction/src/mock.rs
- pallets/auction/src/tests.rs
- pallets/continuum/src/mock.rs
- pallets/currencies/src/mock.rs
- pallets/estate/src/mock.rs
- pallets/governance/src/mock.rs
- pallets/metaverse/src/lib.rs
- pallets/tokenization/src/mock.rs
- runtime/metaverse/src/lib.rs
- runtime/pioneer/src/lib.rs
- runtime/tewai/src/lib.rs
- traits/core-primitives/src/lib.rs
> BCMNP-1851: Network fee for auctions

- pallets/auction/src/lib.rs
There is an issue with comission fee less than the network existential deposit which will cause the destination account failed to be created.
> Feature/commission fee less than ED

- pallets/auction/src/lib.rs
- runtime/pioneer/src/lib.rs
- Runtime upgrade 11 on Pioneer
- Allow Death and error handling on buy now / bid
> Pioneer release 0.0.11

- Cargo.lock
- pallets/economy/src/lib.rs
- pallets/economy/src/tests.rs
- runtime/metaverse/src/lib.rs
- runtime/pioneer/Cargo.toml
- runtime/pioneer/src/lib.rs
- Enable Proxy
- Update CollectiveRatio
- Enable cancel listing
> Pioneer Release 0.0.14

- pallets/metaverse/src/lib.rs
- pallets/nft/src/lib.rs
- pallets/nft/src/mock.rs
- pallets/nft/src/tests.rs
- primitives/metaverse/src/continuum.rs
- primitives/metaverse/src/estate.rs
- primitives/metaverse/src/evm.rs
- primitives/metaverse/src/staking.rs
- runtime/pioneer/src/lib.rs
- traits/auction-manager/src/lib.rs
- traits/core-primitives/src/lib.rs
- New royalty fee set up for estate and land
- New runtime upgrade
- Ability to force update royalty fee
> Pioneer Release 0.0.15

- modules/bridge/src/lib.rs
- modules/bridge/src/mock.rs
- modules/bridge/src/tests.rs
- runtime/metaverse/src/lib.rs
This feature allows multiple fungible token to interact with evm bridge
> Bridge fungible token support
